version: '3'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo        # <-- Add this line
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017/?authSource=admin

  mongo:
    image: mongo
    container_name: local-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
